apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    uptest.upbound.io/timeout: "3600"
    meta.upbound.io/example-id: ec2/v1beta1/instance
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    region: us-east-1
    ami: ami-04cb4ca688797756f
    instanceType: t3.micro
    networkInterface:
    - deviceIndex: 0
      networkInterfaceIdSelector:
        matchLabels:
          testing.upbound.io/example-name: sample-instance
    creditSpecification:
    - cpuCredits: unlimited
