apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sample-subnet1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    vpcIdRef:
      name: sample-vpc
    cidrBlock: 10.2.0.1/24